<a href="https://colab.research.google.com/github/mkdelavina/Data-Analytics-Portfolio/blob/main/colab/Immobilien_Scout_24_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Immoscout](https://raw.githubusercontent.com/juliandnl/redi_ss20/master/image.png)

# Project - Intro to Pandas [Filter and Group]

---
## The description:
Hi all! You're already familiar with the Immobilienscout 24 dataset from the last project. In this project, we will explore the dataset further by sorting, filtering and grouping.

---
## The dataset:
The datasets contains information about rental apartments in Berlin.
One row is for one appartment. The dataset contains 6 columns.  
- Region: is the Berlin district, where the flat is located
- Condition: is the condition of the flat
- Rooms: The number of rooms the flat has
- Rent: Monthly rent for the flat
- Year_Construction: The year in which the house was build
- Space: How many square meters does the flat have?

---
## The Task:
For each question, write code which clearly show the answer to it.

In [1]:
# Imports
import pandas as pd

In [2]:
# Read in dataset
rentals = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/berlin_rental.csv")
rentals.head()

        Region       Condition  Rooms     Rent  Year_Construction   Space
0        Mitte  first_time_use    4.0  2659.00               2019  117.20
1    Kreuzberg  first_time_use    1.0  1200.00               2020   29.33
2     Köpenick       well_kept    2.0   979.00               1997   83.61
3  Wilmersdorf       well_kept    4.0  1830.22               1900  171.18
4    Kreuzberg  first_time_use    2.0  2272.00               2020   88.27

1.How many apartments in Mitte are in a 'well-kept' condition?

In [3]:
rentals.loc[rentals["Condition"] == "well_kept","Condition"].value_counts()

Condition
well_kept    96
Name: count, dtype: int64

In [4]:
rentals.loc[rentals["Region"] == "Mitte" ,"Condition"]

0      first_time_use
6      mint_condition
10     first_time_use
12     first_time_use
15          well_kept
            ...
736         well_kept
741    mint_condition
748    mint_condition
751    no_information
754    no_information
Name: Condition, Length: 153, dtype: str

2.How many apartments in Kreuzberg were built before 1900?

In [5]:
r = rentals.loc[rentals["Year_Construction"] < 1900,"Year_Construction"]
len(r)

37

3.What are the average apartment sizes by the number of rooms?

In [6]:
rentals.groupby("Rooms")["Space"].mean().round(2)

Rooms
1.0     34.47
1.5     41.36
2.0     65.02
2.5     90.46
3.0     99.40
3.5     98.04
4.0    130.86
4.5    106.10
5.0    194.40
6.0    237.00
7.0    251.00
Name: Space, dtype: float64

4.Which is the most expensive region on average and what is the maximum rent for this region?

In [7]:
rentals.groupby("Region")["Rent"].agg(["mean","max"]).sort_values(by=['mean'],ascending=False).reset_index().head(1)

  Region         mean      max
0  Mitte  2408.725033  14207.0

## * Bonus Question:
5. What are the minimum, maximum and average number of rooms of the apartments in Köpenick?

In [8]:
rentals.groupby("Region")["Rooms"].agg(["min","max","mean"]).loc["Köpenick"]

min     1.000000
max     4.000000
mean    2.281818
Name: Köpenick, dtype: float64

## ** Extra Bonus Question
6. Show a table of apartment counts, where rows and columns correspond to year of construction and region, respectively.

In [9]:
year_and_region = rentals.groupby(["Year_Construction","Region"])[["Condition"]].count()
year_and_region.rename(columns={"Condition":"Apartments"}, inplace=True)
year_and_region_wide = pd.pivot_table(year_and_region,values="Apartments",index="Year_Construction",columns="Region")
year_and_region_wide

Region,Charlottenburg,Friedrichsfelde,Kreuzberg,Köpenick,Mitte,Neukölln,Prenzlauer,Tiergarten,Wedding,Wilmersdorf
Year_Construction,,,,,,,,,,
1864,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1867,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1870,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN
1873,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1874,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2016,4.0,1.0,3.0,4.0,12.0,NaN,2.0,NaN,1.0,1.0
2017,2.0,1.0,3.0,2.0,15.0,2.0,1.0,2.0,15.0,2.0
2018,1.0,NaN,1.0,4.0,21.0,4.0,1.0,22.0,2.0,2.0
2019,17.0,6.0,11.0,12.0,21.0,11.0,12.0,85.0,1.0,5.0
2020,6.0,23.0,5.0,NaN,10.0,1.0,NaN,5.0,2.0,6.0

# ⚠ Optional but important

Colab notebooks are great to show code in class, but you shall be able to run python code on your own machine (it probably has more memory than Colab, which could be usefull during the final projects, for example).

One easy option is to use Jupyter notebook (Colab is actually based on that).


<font color='blue'><b> INSTRUCTIONS TO INSTALL JUPYTER NOTEBOOK</b></font>

* Go to the terminal (the command prompt) on your machine and install jupyter notebook with:
`pip install jupyterlab`
* Then, still in the terminal, install pandas with:
`pip install pandas`
* Finally, still in the terminal, open a jupyter notebook with:
`jupyter notebook`
* It may open a browser directly, or give you a URL to paste in a browser, do it.
* In the page opened in the browser, go to New > Python3 (it's on the right)
* There you shall be able to run the same code as in a Colab notebok.


Try it and let the teachers know if you run into issues.